### ISSUE TITLE
Diamond Jellyfish can't be caught

### ISSUE THREAD

**Issue by Lilya030** [BlueDuckYT/Jellyfishing#15]
hi there! my friend and I are using your mod, and we can't catch the diamond jellyfish! We've caught every other jellyfish (bar the netherite, of course) no problems, but when we use the jellyfishing net on the diamond jellyfish, it doesn't do anything. Are we missing something? 
We're using Jellyfishing as part of the Ragnamod VI 6.1.6 modpack.

**Comment by BlueDuckYT** [comment]
They're difficult to catch by design.  The agility enchantment will help your chances of catching them
