### ISSUE TITLE
Unregistered ConfiguredFeatures

### ISSUE THREAD

**Issue by bessiq** [BlueDuckYT/Jellyfishing#5]
Hi there,

Love the mod, and just wanted to supply some log info from the Blame mod regarding your configured features:
https://hatebin.com/spdfokrwun

I'm currently on Forge 36.0.14 and Jellyfishing 1.6.5, but I've seen this in my logs since older versions of Forge and Jellyfishing (just forgot to mention it until now). I tested with just Jellyfishing and a few client-side mods like JEI, The One Probe, etc.

Let me know if you need any other info. Thanks!

**Comment by BlueDuckYT** [comment]
Fixed in latest patch (1.6.7)
