### ISSUE TITLE
Broken Scrap Window Recipe 

### ISSUE THREAD

**Issue by ChrisLTheNerd** [BlueDuckYT/Jellyfishing#6]
There is no recipe for the scrap metal window, trying to craft it with glass in the middle makes the vault trapdoor.
![2021-02-03_14 50 46](https://user-images.githubusercontent.com/50182206/106801352-a6087400-662f-11eb-92cf-48a204582a5c.png)
Here it is without just enough items
![2021-02-03_14 48 59](https://user-images.githubusercontent.com/50182206/106801386-b28ccc80-662f-11eb-9f21-0a1439d8dc47.png)
![2021-02-03_14 48 48](https://user-images.githubusercontent.com/50182206/106801392-b3bdf980-662f-11eb-9ff2-793fbacccd32.png)

**Comment by BlueDuckYT** [comment]
Fixed in latest commit, will push a patch out soon
